// Code generated by goyacc -o predicate.gen.go -p predicate predicate.y. DO NOT EDIT.

//line predicate.y:2

package predicate

import __yyfmt__ "fmt"

//line predicate.y:3

//line predicate.y:7
type predicateSymType struct {
	yys       int
	tree      *Tree
	operator  *OperatorType
	operators []*OperatorType
	ident     *Ident
	lit       *LiteralExpr
	lits      *LiteralListExpr
	fields    *FieldsExpr
	expr      Expr
	predicate *ComboExpr
}

const COMMA = 57346
const DOT = 57347
const LPAREN = 57348
const RPAREN = 57349
const LBRACK = 57350
const RBRACK = 57351
const END = 57352
const GREATER = 57353
const LESS = 57354
const EQUAL = 57355
const NOT = 57356
const LIKE = 57357
const MATCH = 57358
const IN = 57359
const MINUS = 57360
const AND = 57361
const OR = 57362
const IDENT = 57363
const STRING = 57364
const BOOLEAN = 57365
const INTEGER = 57366
const NULL = 57367

var predicateToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMMA",
	"DOT",
	"LPAREN",
	"RPAREN",
	"LBRACK",
	"RBRACK",
	"END",
	"GREATER",
	"LESS",
	"EQUAL",
	"NOT",
	"LIKE",
	"MATCH",
	"IN",
	"MINUS",
	"AND",
	"OR",
	"IDENT",
	"STRING",
	"BOOLEAN",
	"INTEGER",
	"NULL",
}

var predicateStatenames = [...]string{}

const predicateEofCode = 1
const predicateErrCode = 2
const predicateInitialStackSize = 16

//line predicate.y:217

//line yacctab:1
var predicateExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const predicatePrivate = 57344

const predicateLast = 66

var predicateAct = [...]int8{
	54, 53, 30, 49, 48, 61, 26, 27, 31, 43,
	57, 55, 40, 25, 46, 42, 18, 51, 50, 38,
	37, 24, 19, 20, 13, 14, 15, 16, 17, 4,
	7, 29, 23, 9, 10, 22, 56, 45, 44, 9,
	10, 32, 52, 33, 6, 34, 35, 36, 60, 3,
	41, 60, 1, 62, 58, 47, 59, 39, 21, 2,
	8, 63, 12, 28, 11, 5,
}

var predicatePact = [...]int16{
	23, -1000, 20, -1000, 23, 11, -1000, -1000, 23, 16,
	12, 14, -16, 28, 30, -2, -3, 49, -9, 25,
	24, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-10, 50, -21, -22, -4, -5, 34, -1000, -1000, -16,
	-1000, -1000, -1000, -13, -1000, -1000, 31, -14, -1000, -1000,
	-1000, -1000, -16, 47, -1000, -1000, -19, -1000, 44, -1000,
	-16, -1000, -1000, -1000,
}

var predicatePgo = [...]int8{
	0, 65, 0, 31, 63, 1, 62, 60, 49, 59,
	52,
}

var predicateR1 = [...]int8{
	0, 10, 9, 9, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 6, 6, 6, 6, 6, 6,
	7, 7, 5, 5, 2, 2, 2, 3, 3, 4,
	4, 4, 1, 1, 1,
}

var predicateR2 = [...]int8{
	0, 2, 1, 3, 3, 3, 4, 4, 3, 4,
	3, 4, 5, 6, 1, 1, 2, 2, 2, 2,
	2, 2, 3, 1, 1, 1, 1, 1, 2, 1,
	4, 3, 3, 3, 1,
}

var predicateChk = [...]int16{
	-1000, -10, -9, -8, 6, -1, 21, 10, -7, 19,
	20, -9, -6, 13, 14, 15, 16, 17, 5, 11,
	12, -8, 19, 20, 7, -2, 22, 23, -4, -3,
	18, 24, 13, 13, 15, 16, 17, 22, 22, 8,
	21, -3, 24, 18, 13, 13, 24, 5, 25, 25,
	22, 22, 8, -5, -2, 24, 5, 24, -5, 9,
	4, 24, 9, -2,
}

var predicateDef = [...]int8{
	0, -2, 0, 2, 0, 0, 34, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 14,
	15, 3, 20, 21, 4, 5, 24, 25, 26, 29,
	0, 27, 18, 19, 0, 0, 0, 8, 10, 0,
	32, 33, 27, 0, 16, 17, 28, 0, 6, 7,
	9, 11, 0, 0, 23, 28, 0, 31, 0, 12,
	0, 30, 13, 22,
}

var predicateTok1 = [...]int8{
	1,
}

var predicateTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25,
}

var predicateTok3 = [...]int8{
	0,
}

var predicateErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	predicateDebug        = 0
	predicateErrorVerbose = false
)

type predicateLexer interface {
	Lex(lval *predicateSymType) int
	Error(s string)
}

type predicateParser interface {
	Parse(predicateLexer) int
	Lookahead() int
}

type predicateParserImpl struct {
	lval  predicateSymType
	stack [predicateInitialStackSize]predicateSymType
	char  int
}

func (p *predicateParserImpl) Lookahead() int {
	return p.char
}

func predicateNewParser() predicateParser {
	return &predicateParserImpl{}
}

const predicateFlag = -1000

func predicateTokname(c int) string {
	if c >= 1 && c-1 < len(predicateToknames) {
		if predicateToknames[c-1] != "" {
			return predicateToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func predicateStatname(s int) string {
	if s >= 0 && s < len(predicateStatenames) {
		if predicateStatenames[s] != "" {
			return predicateStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func predicateErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !predicateErrorVerbose {
		return "syntax error"
	}

	for _, e := range predicateErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + predicateTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(predicatePact[state])
	for tok := TOKSTART; tok-1 < len(predicateToknames); tok++ {
		if n := base + tok; n >= 0 && n < predicateLast && int(predicateChk[int(predicateAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if predicateDef[state] == -2 {
		i := 0
		for predicateExca[i] != -1 || int(predicateExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; predicateExca[i] >= 0; i += 2 {
			tok := int(predicateExca[i])
			if tok < TOKSTART || predicateExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if predicateExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += predicateTokname(tok)
	}
	return res
}

func predicatelex1(lex predicateLexer, lval *predicateSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(predicateTok1[0])
		goto out
	}
	if char < len(predicateTok1) {
		token = int(predicateTok1[char])
		goto out
	}
	if char >= predicatePrivate {
		if char < predicatePrivate+len(predicateTok2) {
			token = int(predicateTok2[char-predicatePrivate])
			goto out
		}
	}
	for i := 0; i < len(predicateTok3); i += 2 {
		token = int(predicateTok3[i+0])
		if token == char {
			token = int(predicateTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(predicateTok2[1]) /* unknown char */
	}
	if predicateDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", predicateTokname(token), uint(char))
	}
	return char, token
}

func predicateParse(predicatelex predicateLexer) int {
	return predicateNewParser().Parse(predicatelex)
}

func (predicatercvr *predicateParserImpl) Parse(predicatelex predicateLexer) int {
	var predicaten int
	var predicateVAL predicateSymType
	var predicateDollar []predicateSymType
	_ = predicateDollar // silence set and not used
	predicateS := predicatercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	predicatestate := 0
	predicatercvr.char = -1
	predicatetoken := -1 // predicatercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		predicatestate = -1
		predicatercvr.char = -1
		predicatetoken = -1
	}()
	predicatep := -1
	goto predicatestack

ret0:
	return 0

ret1:
	return 1

predicatestack:
	/* put a state and value onto the stack */
	if predicateDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", predicateTokname(predicatetoken), predicateStatname(predicatestate))
	}

	predicatep++
	if predicatep >= len(predicateS) {
		nyys := make([]predicateSymType, len(predicateS)*2)
		copy(nyys, predicateS)
		predicateS = nyys
	}
	predicateS[predicatep] = predicateVAL
	predicateS[predicatep].yys = predicatestate

predicatenewstate:
	predicaten = int(predicatePact[predicatestate])
	if predicaten <= predicateFlag {
		goto predicatedefault /* simple state */
	}
	if predicatercvr.char < 0 {
		predicatercvr.char, predicatetoken = predicatelex1(predicatelex, &predicatercvr.lval)
	}
	predicaten += predicatetoken
	if predicaten < 0 || predicaten >= predicateLast {
		goto predicatedefault
	}
	predicaten = int(predicateAct[predicaten])
	if int(predicateChk[predicaten]) == predicatetoken { /* valid shift */
		predicatercvr.char = -1
		predicatetoken = -1
		predicateVAL = predicatercvr.lval
		predicatestate = predicaten
		if Errflag > 0 {
			Errflag--
		}
		goto predicatestack
	}

predicatedefault:
	/* default state action */
	predicaten = int(predicateDef[predicatestate])
	if predicaten == -2 {
		if predicatercvr.char < 0 {
			predicatercvr.char, predicatetoken = predicatelex1(predicatelex, &predicatercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if predicateExca[xi+0] == -1 && int(predicateExca[xi+1]) == predicatestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			predicaten = int(predicateExca[xi+0])
			if predicaten < 0 || predicaten == predicatetoken {
				break
			}
		}
		predicaten = int(predicateExca[xi+1])
		if predicaten < 0 {
			goto ret0
		}
	}
	if predicaten == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			predicatelex.Error(predicateErrorMessage(predicatestate, predicatetoken))
			Nerrs++
			if predicateDebug >= 1 {
				__yyfmt__.Printf("%s", predicateStatname(predicatestate))
				__yyfmt__.Printf(" saw %s\n", predicateTokname(predicatetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for predicatep >= 0 {
				predicaten = int(predicatePact[predicateS[predicatep].yys]) + predicateErrCode
				if predicaten >= 0 && predicaten < predicateLast {
					predicatestate = int(predicateAct[predicaten]) /* simulate a shift of "error" */
					if int(predicateChk[predicatestate]) == predicateErrCode {
						goto predicatestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if predicateDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", predicateS[predicatep].yys)
				}
				predicatep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if predicateDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", predicateTokname(predicatetoken))
			}
			if predicatetoken == predicateEofCode {
				goto ret1
			}
			predicatercvr.char = -1
			predicatetoken = -1
			goto predicatenewstate /* try again in the same state */
		}
	}

	/* reduction by production predicaten */
	if predicateDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", predicaten, predicateStatname(predicatestate))
	}

	predicatent := predicaten
	predicatept := predicatep
	_ = predicatept // guard against "declared and not used"

	predicatep -= int(predicateR2[predicaten])
	// predicatep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if predicatep+1 >= len(predicateS) {
		nyys := make([]predicateSymType, len(predicateS)*2)
		copy(nyys, predicateS)
		predicateS = nyys
	}
	predicateVAL = predicateS[predicatep+1]

	/* consult goto table to find next state */
	predicaten = int(predicateR1[predicaten])
	predicateg := int(predicatePgo[predicaten])
	predicatej := predicateg + predicateS[predicatep].yys + 1

	if predicatej >= predicateLast {
		predicatestate = int(predicateAct[predicateg])
	} else {
		predicatestate = int(predicateAct[predicatej])
		if int(predicateChk[predicatestate]) != -predicaten {
			predicatestate = int(predicateAct[predicateg])
		}
	}
	// dummy call; replaced with literal code
	switch predicatent {

	case 1:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:36
		{
			predicateVAL.tree.Expr = predicateDollar[1].predicate
		}
	case 2:
		predicateDollar = predicateS[predicatept-1 : predicatept+1]
//line predicate.y:42
		{
			predicateVAL.predicate.Items = []ComboItem{predicateDollar[1].expr}
		}
	case 3:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:46
		{
			predicateVAL.predicate.Items = append(predicateDollar[1].predicate.Items, predicateDollar[2].operators)
			predicateVAL.predicate.Items = append(predicateDollar[1].predicate.Items, predicateDollar[3].expr)
		}
	case 4:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:53
		{
			predicateVAL.expr = &ParenExpr{
				Expr: predicateDollar[2].predicate,
			}
		}
	case 5:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:59
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    predicateDollar[2].operators,
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[3].lit,
			}
		}
	case 6:
		predicateDollar = predicateS[predicatept-4 : predicatept+1]
//line predicate.y:67
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator, predicateDollar[3].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[4].lit,
			}
		}
	case 7:
		predicateDollar = predicateS[predicatept-4 : predicatept+1]
//line predicate.y:75
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator, predicateDollar[3].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[4].lit,
			}
		}
	case 8:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:83
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[3].lit,
			}
		}
	case 9:
		predicateDollar = predicateS[predicatept-4 : predicatept+1]
//line predicate.y:91
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator, predicateDollar[3].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[4].lit,
			}
		}
	case 10:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:99
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[3].lit,
			}
		}
	case 11:
		predicateDollar = predicateS[predicatept-4 : predicatept+1]
//line predicate.y:107
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator, predicateDollar[3].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[4].lit,
			}
		}
	case 12:
		predicateDollar = predicateS[predicatept-5 : predicatept+1]
//line predicate.y:115
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[4].lits,
			}
		}
	case 13:
		predicateDollar = predicateS[predicatept-6 : predicatept+1]
//line predicate.y:123
		{
			predicateVAL.expr = &BinaryExpr{
				Op:    []*OperatorType{predicateDollar[2].operator, predicateDollar[3].operator},
				Left:  predicateDollar[1].fields,
				Right: predicateDollar[5].lits,
			}
		}
	case 14:
		predicateDollar = predicateS[predicatept-1 : predicatept+1]
//line predicate.y:133
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator}
		}
	case 15:
		predicateDollar = predicateS[predicatept-1 : predicatept+1]
//line predicate.y:137
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator}
		}
	case 16:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:141
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator, predicateDollar[2].operator}
		}
	case 17:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:145
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator, predicateDollar[2].operator}
		}
	case 18:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:149
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator, predicateDollar[2].operator}
		}
	case 19:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:153
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator, predicateDollar[2].operator}
		}
	case 20:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:159
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator, predicateDollar[2].operator}
		}
	case 21:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:163
		{
			predicateVAL.operators = []*OperatorType{predicateDollar[1].operator, predicateDollar[2].operator}
		}
	case 22:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:169
		{
			predicateVAL.lits.List = append(predicateDollar[1].lits.List, predicateDollar[3].lit)
		}
	case 23:
		predicateDollar = predicateS[predicatept-1 : predicatept+1]
//line predicate.y:173
		{
			predicateVAL.lits.List = []*LiteralExpr{predicateDollar[1].lit}
		}
	case 28:
		predicateDollar = predicateS[predicatept-2 : predicatept+1]
//line predicate.y:185
		{
			predicateDollar[2].lit.Value = "-" + predicateDollar[2].lit.Value
			predicateVAL.lit = predicateDollar[2].lit
		}
	case 30:
		predicateDollar = predicateS[predicatept-4 : predicatept+1]
//line predicate.y:193
		{
			predicateDollar[2].lit.Value = "-" + predicateDollar[2].lit.Value + "." + predicateDollar[4].lit.Value
			predicateVAL.lit = predicateDollar[2].lit
		}
	case 31:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:198
		{
			predicateDollar[1].lit.Value = predicateDollar[1].lit.Value + "." + predicateDollar[3].lit.Value
			predicateVAL.lit = predicateDollar[1].lit
		}
	case 32:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:205
		{
			predicateVAL.fields.Fields = append(predicateDollar[1].fields.Fields, predicateDollar[3].ident)
		}
	case 33:
		predicateDollar = predicateS[predicatept-3 : predicatept+1]
//line predicate.y:209
		{
			predicateVAL.fields.Fields = append(predicateDollar[1].fields.Fields, predicateDollar[3].lit)
		}
	case 34:
		predicateDollar = predicateS[predicatept-1 : predicatept+1]
//line predicate.y:213
		{
			predicateVAL.fields.Fields = append(predicateVAL.fields.Fields, predicateDollar[1].ident)
		}
	}
	goto predicatestack /* stack new state and value */
}
